# Generated by Django 6.1.1 on 2026-09-24 06:42

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('account', 'AccountInterface'), ('room', 'RoomInterface'), ('thread', 'ThreadInterface'), ('thread_post', 'ThreadPostInterface')], max_length=24)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('account', 'AccountInterface'), ('room', 'RoomInterface'), ('thread', 'ThreadInterface'), ('thread_post', 'ThreadPostInterface')], default='thread', max_length=24)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_drafts', to=settings.AUTH_USER_MODEL)),
                ('interface', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='interfaces.interface')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='interfaces.interface')),
            ],
            options={
                'ordering': ['interface_id', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('required_interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='version_dependents', to='interfaces.interface')),
                ('required_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolved_dependents', to='interfaces.interfaceversion')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='interfaces.interfaceversion')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('short_text', '一行テキスト'), ('long_text', '複数行テキスト'), ('integer', '整数'), ('decimal', '小数'), ('date', '日付'), ('datetime', '日時'), ('boolean', '真偽値'), ('single_choice', '単一選択'), ('multiple_choice', '複数選択')], max_length=24)),
                ('required', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='interfaces.interfaceversion')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='interface',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='interfaces.interfaceversion'),
        ),
        migrations.CreateModel(
            name='InterfaceDraftField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('short_text', '一行テキスト'), ('long_text', '複数行テキスト'), ('integer', '整数'), ('decimal', '小数'), ('date', '日付'), ('datetime', '日時'), ('boolean', '真偽値'), ('single_choice', '単一選択'), ('multiple_choice', '複数選択')], max_length=24)),
                ('required', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='interfaces.interfacedraft')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('draft', 'field_key'), name='unique_draft_field_key'), models.UniqueConstraint(fields=('draft', 'position'), name='unique_draft_field_position')],
            },
        ),
        migrations.CreateModel(
            name='InterfaceDraftRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='interfaces.interfacedraft')),
                ('required_interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_dependents', to='interfaces.interface')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('draft', 'required_interface'), name='unique_draft_requirement'), models.UniqueConstraint(fields=('draft', 'position'), name='unique_draft_requirement_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='interfaceversion',
            constraint=models.UniqueConstraint(fields=('interface', 'version_number'), name='unique_interface_version_number'),
        ),
        migrations.AddConstraint(
            model_name='interfacerequirement',
            constraint=models.UniqueConstraint(fields=('version', 'required_interface'), name='unique_version_requirement'),
        ),
        migrations.AddConstraint(
            model_name='interfacerequirement',
            constraint=models.UniqueConstraint(fields=('version', 'position'), name='unique_version_requirement_position'),
        ),
        migrations.AddConstraint(
            model_name='interfacefield',
            constraint=models.UniqueConstraint(fields=('version', 'field_key'), name='unique_version_field_key'),
        ),
        migrations.AddConstraint(
            model_name='interfacefield',
            constraint=models.UniqueConstraint(fields=('version', 'position'), name='unique_version_field_position'),
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('creator'), name='unique_interface_name_per_creator'),
        ),
    ]
