# Generated by Django 6.1.1 on 2026-09-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_default_to_show_guest_threads'),
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadInterfaceImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_implementations', to='interfaces.interface')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_implementations', to='events.thread')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_implementations', to='interfaces.interfaceversion')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ThreadInterfaceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_values', to='interfaces.interfacefield')),
                ('implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='interfaces.threadinterfaceimplementation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='threadinterfaceimplementation',
            constraint=models.UniqueConstraint(fields=('thread', 'interface'), name='unique_thread_interface'),
        ),
        migrations.AddConstraint(
            model_name='threadinterfaceimplementation',
            constraint=models.UniqueConstraint(fields=('thread', 'position'), name='unique_thread_interface_position'),
        ),
        migrations.AddConstraint(
            model_name='threadinterfacevalue',
            constraint=models.UniqueConstraint(fields=('implementation', 'field'), name='unique_thread_interface_field_value'),
        ),
    ]
