# Generated by Django 6.1.1 on 2026-09-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_threadinterfaceimplementation_threadinterfacevalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='kind',
            field=models.CharField(choices=[('account', 'AccountIF'), ('room', 'RoomIF'), ('thread', 'ThreadIF'), ('thread_post', 'ResponseIF')], max_length=24),
        ),
        migrations.AlterField(
            model_name='interfacedraft',
            name='kind',
            field=models.CharField(choices=[('account', 'AccountIF'), ('room', 'RoomIF'), ('thread', 'ThreadIF'), ('thread_post', 'ResponseIF')], default='thread', max_length=24),
        ),
    ]
