# Generated by Django 6.1.1 on 2026-09-29 12:50

import django.db.models.deletion
import django.db.models.functions.text
import json
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_inline_fields(apps, schema_editor):
    FieldDefinition = apps.get_model('interfaces', 'FieldDefinition')
    FieldVersion = apps.get_model('interfaces', 'FieldVersion')
    InterfaceDraftField = apps.get_model('interfaces', 'InterfaceDraftField')
    InterfaceDraftRequirement = apps.get_model('interfaces', 'InterfaceDraftRequirement')
    InterfaceField = apps.get_model('interfaces', 'InterfaceField')
    InterfaceRequirement = apps.get_model('interfaces', 'InterfaceRequirement')
    ThreadFieldBinding = apps.get_model('interfaces', 'ThreadFieldBinding')
    ThreadFieldValue = apps.get_model('interfaces', 'ThreadFieldValue')
    ThreadInterfaceValue = apps.get_model('interfaces', 'ThreadInterfaceValue')

    definitions = {}
    versions = {}

    def available_name(creator_id, preferred, interface_name):
        base = preferred[:120]
        if not FieldDefinition.objects.filter(creator_id=creator_id, name__iexact=base).exists():
            return base
        stem = f'{preferred} ({interface_name})'
        candidate = stem[:120]
        index = 2
        while FieldDefinition.objects.filter(creator_id=creator_id, name__iexact=candidate).exists():
            suffix = f' {index}'
            candidate = f'{stem[:120 - len(suffix)]}{suffix}'
            index += 1
        return candidate

    fields = InterfaceField.objects.select_related('version__interface').order_by(
        'version__interface_id',
        'version__version_number',
        'position',
        'pk',
    )
    for interface_field in fields:
        interface = interface_field.version.interface
        identity = (interface.pk, interface_field.field_key)
        definition = definitions.get(identity)
        if definition is None:
            definition = FieldDefinition.objects.create(
                creator_id=interface.creator_id,
                key=interface_field.field_key,
                name=available_name(interface.creator_id, interface_field.label, interface.name),
            )
            definitions[identity] = definition

        schema_key = (
            definition.pk,
            interface_field.label,
            interface_field.field_type,
            json.dumps(interface_field.settings, sort_keys=True, ensure_ascii=True),
        )
        field_version = versions.get(schema_key)
        if field_version is None:
            field_version = FieldVersion.objects.create(
                definition=definition,
                version_number=definition.versions.count() + 1,
                name=interface_field.label,
                field_type=interface_field.field_type,
                settings=interface_field.settings,
            )
            versions[schema_key] = field_version
            definition.current_version = field_version
            definition.save(update_fields=['current_version', 'updated_at'])

        interface_field.definition = definition
        interface_field.field_version = field_version
        interface_field.save(update_fields=['definition', 'field_version'])

    draft_fields = InterfaceDraftField.objects.select_related('draft__interface').order_by('pk')
    for draft_field in draft_fields:
        definition = None
        if draft_field.draft.interface_id:
            definition = definitions.get((draft_field.draft.interface_id, draft_field.field_key))
        if definition is None:
            creator_id = draft_field.draft.creator_id
            context_name = draft_field.draft.name or 'Draft'
            definition = FieldDefinition.objects.create(
                creator_id=creator_id,
                key=draft_field.field_key,
                name=available_name(creator_id, draft_field.label, context_name),
            )
            field_version = FieldVersion.objects.create(
                definition=definition,
                version_number=1,
                name=draft_field.label,
                field_type=draft_field.field_type,
                settings=draft_field.settings,
            )
            definition.current_version = field_version
            definition.save(update_fields=['current_version', 'updated_at'])
        draft_field.definition = definition
        draft_field.save(update_fields=['definition'])

    for requirement in InterfaceRequirement.objects.select_related('version', 'required_version').order_by(
        'version_id', 'position', 'pk'
    ):
        existing_definition_ids = set(
            InterfaceField.objects.filter(version_id=requirement.version_id).values_list(
                'definition_id', flat=True
            )
        )
        last_position = InterfaceField.objects.filter(version_id=requirement.version_id).order_by(
            '-position'
        ).values_list('position', flat=True).first()
        position = 0 if last_position is None else last_position + 1
        required_fields = InterfaceField.objects.filter(
            version_id=requirement.required_version_id
        ).order_by('position', 'pk')
        for required_field in required_fields:
            if required_field.definition_id in existing_definition_ids:
                continue
            InterfaceField.objects.create(
                version_id=requirement.version_id,
                definition_id=required_field.definition_id,
                field_version_id=required_field.field_version_id,
                field_key=required_field.field_key,
                label=required_field.label,
                field_type=required_field.field_type,
                required=required_field.required,
                settings=required_field.settings,
                position=position,
            )
            existing_definition_ids.add(required_field.definition_id)
            position += 1

    for requirement in InterfaceDraftRequirement.objects.select_related('draft').order_by(
        'draft_id', 'position', 'pk'
    ):
        required_version_id = requirement.required_interface.current_version_id
        if required_version_id is None:
            continue
        existing_definition_ids = set(
            InterfaceDraftField.objects.filter(draft_id=requirement.draft_id).values_list(
                'definition_id', flat=True
            )
        )
        last_position = InterfaceDraftField.objects.filter(draft_id=requirement.draft_id).order_by(
            '-position'
        ).values_list('position', flat=True).first()
        position = 0 if last_position is None else last_position + 1
        required_fields = InterfaceField.objects.filter(
            version_id=required_version_id
        ).order_by('position', 'pk')
        for required_field in required_fields:
            if required_field.definition_id in existing_definition_ids:
                continue
            InterfaceDraftField.objects.create(
                draft_id=requirement.draft_id,
                definition_id=required_field.definition_id,
                field_key=required_field.field_key,
                label=required_field.label,
                field_type=required_field.field_type,
                required=required_field.required,
                settings=required_field.settings,
                position=position,
            )
            existing_definition_ids.add(required_field.definition_id)
            position += 1

    thread_values = ThreadInterfaceValue.objects.select_related(
        'implementation__thread',
        'field__definition',
    ).order_by('implementation__created_at', 'pk')
    for interface_value in thread_values:
        thread_id = interface_value.implementation.thread_id
        definition_id = interface_value.field.definition_id
        binding = ThreadFieldBinding.objects.filter(
            thread_id=thread_id,
            definition_id=definition_id,
        ).first()
        if binding is None:
            value = ThreadFieldValue.objects.create(
                thread_id=thread_id,
                value=interface_value.value,
            )
            binding = ThreadFieldBinding.objects.create(
                thread_id=thread_id,
                definition_id=definition_id,
                value=value,
            )
        interface_value.binding = binding
        interface_value.save(update_fields=['binding'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_default_to_show_guest_threads'),
        ('interfaces', '0003_alter_interface_kind_alter_interfacedraft_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='interfacedraftfield',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_interface_bindings', to='interfaces.fielddefinition'),
        ),
        migrations.AddField(
            model_name='interfacefield',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interface_bindings', to='interfaces.fielddefinition'),
        ),
        migrations.CreateModel(
            name='FieldVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('field_type', models.CharField(choices=[('short_text', '一行テキスト'), ('long_text', '複数行テキスト'), ('integer', '整数'), ('decimal', '小数'), ('date', '日付'), ('datetime', '日時'), ('boolean', '真偽値'), ('single_choice', '単一選択'), ('multiple_choice', '複数選択')], max_length=24)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='interfaces.fielddefinition')),
            ],
            options={
                'ordering': ['definition_id', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='FieldSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='synonym_sources', to='interfaces.fielddefinition')),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='interfaces.fieldversion')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='interfaces.fieldversion'),
        ),
        migrations.AddField(
            model_name='interfacefield',
            name='field_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interface_bindings', to='interfaces.fieldversion'),
        ),
        migrations.CreateModel(
            name='ThreadFieldBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_bindings', to='interfaces.fielddefinition')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_bindings', to='events.thread')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='threadinterfacevalue',
            name='binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interface_values', to='interfaces.threadfieldbinding'),
        ),
        migrations.CreateModel(
            name='ThreadFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='events.thread')),
            ],
        ),
        migrations.AddField(
            model_name='threadfieldbinding',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='interfaces.threadfieldvalue'),
        ),
        migrations.AddConstraint(
            model_name='fieldversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version_number'), name='unique_field_version_number'),
        ),
        migrations.AddConstraint(
            model_name='fieldsynonym',
            constraint=models.UniqueConstraint(fields=('source_version', 'target'), name='unique_field_synonym_target'),
        ),
        migrations.AddConstraint(
            model_name='fieldsynonym',
            constraint=models.UniqueConstraint(fields=('source_version', 'position'), name='unique_field_synonym_position'),
        ),
        migrations.AddConstraint(
            model_name='fielddefinition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('creator'), name='unique_field_name_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='threadfieldbinding',
            constraint=models.UniqueConstraint(fields=('thread', 'definition'), name='unique_thread_field_binding'),
        ),
        migrations.RunPython(migrate_inline_fields, migrations.RunPython.noop),
    ]
