# Generated by Django 6.1.1 on 2026-10-02 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_thread_discover_rules'),
        ('interfaces', '0005_use_independent_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadDirectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_implementations', to='interfaces.threadfieldbinding')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_thread_implementations', to='interfaces.fielddefinition')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_fields', to='events.thread')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_thread_implementations', to='interfaces.fieldversion')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('thread', 'definition'), name='unique_thread_direct_field'), models.UniqueConstraint(fields=('thread', 'position'), name='unique_thread_direct_field_position')],
            },
        ),
    ]
