# Generated by Django 6.1.1 on 2026-10-05 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0006_threaddirectfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountFieldBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_bindings', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_bindings', to='interfaces.fielddefinition')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='interfaces.accountfieldvalue')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AccountInterfaceImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_implementations', to=settings.AUTH_USER_MODEL)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_implementations', to='interfaces.interface')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_implementations', to='interfaces.interfaceversion')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AccountInterfaceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interface_values', to='interfaces.accountfieldbinding')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_values', to='interfaces.interfacefield')),
                ('implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='interfaces.accountinterfaceimplementation')),
            ],
        ),
        migrations.CreateModel(
            name='AccountDirectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_fields', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_account_implementations', to='interfaces.fielddefinition')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_account_implementations', to='interfaces.fieldversion')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_implementations', to='interfaces.accountfieldbinding')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('account', 'definition'), name='unique_account_direct_field'), models.UniqueConstraint(fields=('account', 'position'), name='unique_account_direct_field_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='accountfieldbinding',
            constraint=models.UniqueConstraint(fields=('account', 'definition'), name='unique_account_field_binding'),
        ),
        migrations.AddConstraint(
            model_name='accountinterfaceimplementation',
            constraint=models.UniqueConstraint(fields=('account', 'interface'), name='unique_account_interface'),
        ),
        migrations.AddConstraint(
            model_name='accountinterfaceimplementation',
            constraint=models.UniqueConstraint(fields=('account', 'position'), name='unique_account_interface_position'),
        ),
        migrations.AddConstraint(
            model_name='accountinterfacevalue',
            constraint=models.UniqueConstraint(fields=('implementation', 'field'), name='unique_account_interface_field_value'),
        ),
    ]
