# Generated by Django 6.1.1 on 2026-10-05 11:28

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0008_account_application_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AccountLayoutDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='新しいAccountLayout', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('html', models.TextField(blank=True, default='')),
                ('css', models.TextField(blank=True, default='')),
                ('requirements', models.JSONField(default=dict)),
                ('items', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_layout_drafts', to=settings.AUTH_USER_MODEL)),
                ('layout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='interfaces.accountlayout')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLayoutVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('html', models.TextField(blank=True, default='')),
                ('css', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='interfaces.accountlayout')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLayoutRequireIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layout_requirements', to='interfaces.interfaceversion')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='require_interfaces', to='interfaces.accountlayoutversion')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLayoutRequireField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layout_requirements', to='interfaces.fieldversion')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='require_fields', to='interfaces.accountlayoutversion')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=32)),
                ('field_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layout_items', to='interfaces.fieldversion')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='interfaces.accountlayoutversion')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLayoutApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout_application', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='interfaces.accountlayoutversion')),
            ],
        ),
        migrations.AddField(
            model_name='accountlayout',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='interfaces.accountlayoutversion'),
        ),
        migrations.AddConstraint(
            model_name='accountlayoutversion',
            constraint=models.UniqueConstraint(fields=('layout', 'version_number'), name='unique_account_layout_version'),
        ),
        migrations.AddConstraint(
            model_name='accountlayoutrequireif',
            constraint=models.UniqueConstraint(fields=('version', 'interface_version'), name='unique_layout_require_if'),
        ),
        migrations.AddConstraint(
            model_name='accountlayoutrequirefield',
            constraint=models.UniqueConstraint(fields=('version', 'field_version'), name='unique_layout_require_field'),
        ),
        migrations.AddConstraint(
            model_name='accountlayoutitem',
            constraint=models.UniqueConstraint(fields=('version', 'alias'), name='unique_layout_item_alias'),
        ),
        migrations.AddConstraint(
            model_name='accountlayout',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('creator'), name='unique_account_layout_name'),
        ),
    ]
