# Generated by Django 6.1.1 on 2026-10-05 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0009_account_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('submission_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceListReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interface_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='interfaces.interfacelist')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_references', to='interfaces.interface')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('fav', 'fav'), ('bad', 'bad')], max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_ratings', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='interfaces.interface')),
            ],
        ),
        migrations.AddConstraint(
            model_name='interfacelist',
            constraint=models.UniqueConstraint(fields=('owner', 'submission_id'), name='unique_interface_list_submission'),
        ),
        migrations.AddConstraint(
            model_name='interfacelistreference',
            constraint=models.UniqueConstraint(fields=('interface_list', 'target'), name='unique_interface_list_reference'),
        ),
        migrations.AddConstraint(
            model_name='interfacerating',
            constraint=models.UniqueConstraint(fields=('author', 'target'), name='unique_interface_rating'),
        ),
        migrations.AddConstraint(
            model_name='interfacerating',
            constraint=models.CheckConstraint(condition=models.Q(('sentiment__in', ['fav', 'bad'])), name='interface_rating_sentiment'),
        ),
    ]
