# Generated by Django 6.1.1 on 2026-10-06 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0010_content_lists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldListReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interface_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_references', to='interfaces.interfacelist')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_references', to='interfaces.fielddefinition')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('interface_list', 'target'), name='unique_field_list_reference')],
            },
        ),
        migrations.CreateModel(
            name='FieldRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('fav', 'fav'), ('bad', 'bad')], max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_ratings', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='interfaces.fielddefinition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('author', 'target'), name='unique_field_rating'), models.CheckConstraint(condition=models.Q(('sentiment__in', ['fav', 'bad'])), name='field_rating_sentiment')],
            },
        ),
        migrations.CreateModel(
            name='LayoutListReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interface_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_references', to='interfaces.interfacelist')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_references', to='interfaces.accountlayout')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('interface_list', 'target'), name='unique_layout_list_reference')],
            },
        ),
        migrations.CreateModel(
            name='LayoutRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('fav', 'fav'), ('bad', 'bad')], max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_ratings', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='interfaces.accountlayout')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('author', 'target'), name='unique_layout_rating'), models.CheckConstraint(condition=models.Q(('sentiment__in', ['fav', 'bad'])), name='layout_rating_sentiment')],
            },
        ),
    ]
