# Generated by Django 6.1.1 on 2026-09-14 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Event名')),
                ('description', models.TextField(blank=True, verbose_name='Event詳細')),
                ('starts_at', models.DateTimeField(verbose_name='開始日時')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('venue_name', models.CharField(blank=True, max_length=120, verbose_name='会場名')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='経度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'ordering': ['starts_at', 'created_at'],
            },
        ),
    ]
