# Generated by Django 6.1.1 on 2026-09-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=16, unique=True, verbose_name='駅コード')),
                ('group_code', models.CharField(max_length=16, verbose_name='駅グループコード')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='駅名')),
                ('line_name', models.CharField(max_length=120, verbose_name='路線名')),
                ('operator_name', models.CharField(max_length=120, verbose_name='運営会社')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='経度')),
            ],
            options={
                'ordering': ['name', 'line_name'],
            },
        ),
    ]
