# Generated by Django 6.1.1 on 2026-09-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_address_remove_event_venue_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=16)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'ordering': ['kind', 'full_name'],
            },
        ),
    ]
