# Generated by Django 6.1.1 on 2026-09-16

import uuid

from django.db import migrations, models


def populate_submission_ids(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.filter(submission_id__isnull=True).iterator():
        event.submission_id = uuid.uuid4()
        event.save(update_fields=['submission_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='submission_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_submission_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='submission_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
