# Generated by Django 6.1.1 on 2026-09-18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_event_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiiMapFilterPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_filter_enabled', models.BooleanField(default=True)),
                ('show_ongoing', models.BooleanField(default=False)),
                ('show_today', models.BooleanField(default=False)),
                ('show_tomorrow', models.BooleanField(default=False)),
                ('show_ended', models.BooleanField(default=False)),
                ('show_guest_events', models.BooleanField(default=False)),
                ('account_ids_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='niimap_filter_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
