# Generated by Django 6.1.1 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_niimapfilterpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='niimapfilterpreference',
            name='account_section_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='niimapfilterpreference',
            name='datetime_section_open',
            field=models.BooleanField(default=False),
        ),
    ]
