# Generated by Django 6.1.1 on 2026-10-03 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def normalize_primary_placements(apps, schema_editor):
    placement_model = apps.get_model('events', 'ThreadPlacement')
    thread_ids = placement_model.objects.order_by().values_list('thread_id', flat=True).distinct()
    for thread_id in thread_ids.iterator():
        placement_ids = list(
            placement_model.objects.filter(thread_id=thread_id).order_by('created_at', 'pk').values_list('pk', flat=True)
        )
        if len(placement_ids) < 2:
            continue
        placement_model.objects.filter(thread_id=thread_id).update(is_primary=False)
        placement_model.objects.filter(pk=placement_ids[0]).update(is_primary=True)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_niimapfilterpreference_search_state'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadplacement',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_placements', to='rooms.board'),
        ),
        migrations.AddField(
            model_name='threadplacement',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='threadplacement',
            name='kind',
            field=models.CharField(choices=[('niimap', 'NiiMap'), ('board', 'Board')], default='niimap', max_length=24),
        ),
        migrations.AlterField(
            model_name='threadplacement',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='threadplacement',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='経度'),
        ),
        migrations.AddConstraint(
            model_name='threadplacement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('board__isnull', True), ('kind', 'niimap'), ('latitude__isnull', False), ('longitude__isnull', False)), models.Q(('board__isnull', False), ('kind', 'board'), ('latitude__isnull', True), ('longitude__isnull', True)), _connector='OR'), name='valid_thread_placement_target'),
        ),
        migrations.RunPython(normalize_primary_placements, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='threadplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('thread',), name='unique_primary_thread_placement'),
        ),
    ]
