# Generated by Django 6.1.1 on 2026-10-05 02:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_threadplacement_board_threadplacement_is_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadPolicyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('view', '閲覧'), ('write', '書込')], max_length=16)),
                ('decision', models.CharField(choices=[('allow', '可能'), ('deny', '不可')], max_length=8)),
                ('group_key', models.UUIDField(default=uuid.uuid4)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(max_length=24)),
                ('definition', models.JSONField(default=dict)),
                ('label', models.CharField(max_length=255)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_conditions', to='events.thread')),
            ],
            options={
                'ordering': ['capability', 'decision', 'group_key', 'position', 'pk'],
            },
        ),
    ]
