# Generated by Django 6.1.1 on 2026-10-06 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_migrate_thread_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('submission_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseListReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='events.responselist')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_references', to='events.threadpost')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ResponseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('fav', 'fav'), ('bad', 'bad')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_written', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='events.threadpost')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('submission_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreadListReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_references', to='events.thread')),
                ('thread_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='events.threadlist')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ThreadRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('fav', 'fav'), ('bad', 'bad')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_written', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='events.thread')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='responselist',
            constraint=models.UniqueConstraint(fields=('owner', 'submission_id'), name='unique_responselist_submission'),
        ),
        migrations.AddConstraint(
            model_name='responselistreference',
            constraint=models.UniqueConstraint(fields=('response_list', 'target'), name='unique_response_list_reference'),
        ),
        migrations.AddConstraint(
            model_name='responserating',
            constraint=models.UniqueConstraint(fields=('author', 'target'), name='unique_responserating'),
        ),
        migrations.AddConstraint(
            model_name='responserating',
            constraint=models.CheckConstraint(condition=models.Q(('sentiment__in', ['fav', 'bad'])), name='responserating_sentiment'),
        ),
        migrations.AddConstraint(
            model_name='threadlist',
            constraint=models.UniqueConstraint(fields=('owner', 'submission_id'), name='unique_threadlist_submission'),
        ),
        migrations.AddConstraint(
            model_name='threadlistreference',
            constraint=models.UniqueConstraint(fields=('thread_list', 'target'), name='unique_thread_list_reference'),
        ),
        migrations.AddConstraint(
            model_name='threadrating',
            constraint=models.UniqueConstraint(fields=('author', 'target'), name='unique_threadrating'),
        ),
        migrations.AddConstraint(
            model_name='threadrating',
            constraint=models.CheckConstraint(condition=models.Q(('sentiment__in', ['fav', 'bad'])), name='threadrating_sentiment'),
        ),
    ]
