# Generated by Django 6.1.1 on 2026-10-03 12:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Room名')),
                ('description', models.TextField(blank=True, default='', max_length=10000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, verbose_name='最終活動日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Collection名')),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, verbose_name='最終活動日時')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='rooms.room')),
            ],
            options={
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Board名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, verbose_name='最終活動日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boards', to=settings.AUTH_USER_MODEL)),
                ('owner_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_boards', to=settings.AUTH_USER_MODEL)),
                ('owner_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_boards', to='rooms.room')),
            ],
            options={
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='参加日時')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rooms.room')),
            ],
            options={
                'ordering': ['joined_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RoomPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='経度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='掲載日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='BoardPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('collection', 'Collection'), ('niimap', 'NiiMap')], max_length=24)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='経度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='掲載日時')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='rooms.board')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_placements', to='rooms.collection')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('collection__isnull', False), ('kind', 'collection'), ('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('collection__isnull', True), ('kind', 'niimap'), ('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='valid_board_placement_target')],
            },
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('room__isnull', True)), models.Q(('account__isnull', True), ('room__isnull', False)), _connector='OR'), name='collection_has_one_container'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False), ('is_main', True)), fields=('account',), name='unique_account_main_collection'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True), ('room__isnull', False)), fields=('room',), name='unique_room_main_collection'),
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_account__isnull', False), ('owner_room__isnull', True)), models.Q(('owner_account__isnull', True), ('owner_room__isnull', False)), _connector='OR'), name='board_has_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='roommembership',
            constraint=models.UniqueConstraint(fields=('room', 'account'), name='unique_room_membership'),
        ),
    ]
