# Generated by Django 6.1.1 on 2026-10-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_board_management'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='board',
            name='board_has_one_owner',
        ),
        migrations.RemoveField(
            model_name='board',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='board',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='board',
            name='owner_account',
        ),
        migrations.RemoveField(
            model_name='board',
            name='owner_room',
        ),
        migrations.RemoveField(
            model_name='board',
            name='status',
        ),
    ]
