# Generated by Django 6.1.1 on 2026-10-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_board_placement_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='詳細'),
        ),
    ]
