# Generated by Django 6.1.1 on 2026-10-04 05:27

from django.conf import settings
from django.db import migrations, models


def preserve_main_role(apps, schema_editor):
    collection_model = apps.get_model('rooms', 'Collection')
    collection_model.objects.filter(is_main=True).update(role='main')


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_board_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_account_main_collection',
        ),
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_room_main_collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='role',
            field=models.CharField(choices=[('custom', 'Custom'), ('main', 'Main'), ('uncategorized', 'Uncategorized')], default='custom', max_length=24),
        ),
        migrations.RunPython(preserve_main_role, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False), ('role__in', ['main', 'uncategorized'])), fields=('account', 'role'), name='unique_account_system_collection'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['main', 'uncategorized']), ('room__isnull', False)), fields=('room', 'role'), name='unique_room_system_collection'),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='is_main',
        ),
    ]
