# Generated by Django 6.1.1 on 2026-10-04 05:46

from django.conf import settings
from django.db import migrations, models


def preserve_uncategorized_role(apps, schema_editor):
    collection_model = apps.get_model('rooms', 'Collection')
    collection_model.objects.filter(role='uncategorized').update(is_uncategorized=True)


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_remove_collection_unique_account_main_collection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_account_system_collection',
        ),
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_room_system_collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='is_uncategorized',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_uncategorized_role, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False), ('is_uncategorized', True)), fields=('account',), name='unique_account_uncategorized_collection'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_uncategorized', True), ('room__isnull', False)), fields=('room',), name='unique_room_uncategorized_collection'),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='role',
        ),
    ]
