# Generated by Django 6.1.1 on 2026-10-04 06:07

from django.db import migrations


def create_uncategorized_collections(apps, schema_editor):
    room_model = apps.get_model('rooms', 'Room')
    collection_model = apps.get_model('rooms', 'Collection')

    for room_id in room_model.objects.values_list('pk', flat=True).iterator():
        collection_model.objects.get_or_create(
            room_id=room_id,
            is_uncategorized=True,
            defaults={'name': '未分類'},
        )

    account_ids = (
        collection_model.objects.filter(account_id__isnull=False)
        .values_list('account_id', flat=True)
        .distinct()
    )
    for account_id in account_ids.iterator():
        collection_model.objects.get_or_create(
            account_id=account_id,
            is_uncategorized=True,
            defaults={'name': '未分類'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_collection_unique_account_system_collection_and_more'),
    ]

    operations = [
        migrations.RunPython(create_uncategorized_collections, migrations.RunPython.noop),
    ]
