# Generated by Django 6.1.1 on 2026-10-04 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_existing_board_policies(apps, schema_editor):
    board_model = apps.get_model('rooms', 'Board')
    condition_model = apps.get_model('rooms', 'BoardPolicyCondition')

    conditions = []
    boards = board_model.objects.filter(
        placement__collection__room__isnull=False,
    ).select_related('placement__collection__room')
    for board in boards.iterator():
        room = board.placement.collection.room
        conditions.extend([
            condition_model(
                board_id=board.pk,
                capability='view',
                decision='allow',
                kind='default',
                definition={'code': 'guest'},
                label='Guest',
            ),
            condition_model(
                board_id=board.pk,
                capability='view',
                decision='allow',
                kind='default',
                definition={'code': 'account'},
                label='NiixyAccount',
            ),
            condition_model(
                board_id=board.pk,
                capability='create_thread',
                decision='allow',
                kind='room',
                definition={'room_id': room.pk, 'relation': 'member'},
                label=f'{room.name}に参加',
            ),
        ])
    condition_model.objects.bulk_create(conditions)


def clear_board_policies(apps, schema_editor):
    apps.get_model('rooms', 'BoardPolicyCondition').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_create_uncategorized_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPolicyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('view', '閲覧'), ('create_thread', 'Thread作成')], max_length=24)),
                ('decision', models.CharField(choices=[('allow', '可能'), ('deny', '不可')], max_length=8)),
                ('group_key', models.UUIDField(default=uuid.uuid4)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(max_length=24)),
                ('definition', models.JSONField(default=dict)),
                ('label', models.CharField(max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_conditions', to='rooms.board')),
            ],
            options={
                'ordering': ['capability', 'decision', 'group_key', 'position', 'pk'],
            },
        ),
        migrations.RunPython(seed_existing_board_policies, clear_board_policies),
    ]
