# Generated by Django 6.1.1 on 2026-10-05 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_board_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardListReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BoardRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('fav', 'fav'), ('bad', 'bad')], max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='list_submission_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('account', 'list_submission_id'), name='unique_board_list_submission'),
        ),
        migrations.AddField(
            model_name='boardlistreference',
            name='board_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='rooms.collection'),
        ),
        migrations.AddField(
            model_name='boardlistreference',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_references', to='rooms.board'),
        ),
        migrations.AddField(
            model_name='boardrating',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardrating',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rooms.board'),
        ),
        migrations.AddConstraint(
            model_name='boardlistreference',
            constraint=models.UniqueConstraint(fields=('board_list', 'target'), name='unique_board_list_reference'),
        ),
        migrations.AddConstraint(
            model_name='boardrating',
            constraint=models.UniqueConstraint(fields=('author', 'target'), name='unique_board_rating'),
        ),
        migrations.AddConstraint(
            model_name='boardrating',
            constraint=models.CheckConstraint(condition=models.Q(('sentiment__in', ['fav', 'bad'])), name='board_rating_sentiment'),
        ),
    ]
