# Generated by Django 6.1.1 on 2026-10-06 02:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_content_lists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_mutes', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muters', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['room', '-created_at', '-id'], name='room_mute_recent')],
                'constraints': [models.UniqueConstraint(fields=('muter', 'room'), name='unique_room_mute')],
            },
        ),
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('love', 'Love'), ('hate', 'Hate')], max_length=4)),
                ('body', models.TextField(max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_room_reviews', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.room')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
                'indexes': [models.Index(fields=['target', '-updated_at', '-id'], name='room_review_recent')],
                'constraints': [models.UniqueConstraint(fields=('author', 'target'), name='unique_room_review'), models.CheckConstraint(condition=models.Q(('sentiment__in', ['love', 'hate'])), name='room_review_sentiment'), models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='room_review_body_required')],
            },
        ),
    ]
