# Generated by Django 6.1.1 on 2026-10-02 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('default', 'Default'), ('account', 'Account'), ('account_interface', 'AccountIF'), ('field', 'Field'), ('room', 'Room')], max_length=24)),
                ('definition', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'fingerprint'), name='unique_account_condition')],
            },
        ),
    ]
