# Generated by Django 6.1.1 on 2026-10-05 13:19

import django.db.models.deletion
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountcondition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('love', 'Love'), ('hate', 'Hate')], max_length=4)),
                ('body', models.TextField(max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
                'indexes': [models.Index(fields=['target', '-updated_at', '-id'], name='account_review_recent')],
                'constraints': [models.UniqueConstraint(fields=('author', 'target'), name='unique_account_review'), models.CheckConstraint(condition=models.Q(('author', models.F('target')), _negated=True), name='account_review_not_self'), models.CheckConstraint(condition=models.Q(('sentiment__in', ['love', 'hate'])), name='account_review_sentiment'), models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='account_review_body_required')],
            },
        ),
    ]
