# Generated by Django 6.1.1 on 2026-10-05 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muted_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_muters', to=settings.AUTH_USER_MODEL)),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['muted_account', '-created_at', '-id'], name='account_mute_recent')],
                'constraints': [models.UniqueConstraint(fields=('muter', 'muted_account'), name='unique_account_mute'), models.CheckConstraint(condition=models.Q(('muter', models.F('muted_account')), _negated=True), name='account_mute_not_self')],
            },
        ),
    ]
